### ISSUE TITLE
About train dataloader length and unsup train dataloader length

### ISSUE THREAD

**Issue by angle011** [YJ-He/ClassHyPer#1]
Hi [YJ-He](https://github.com/YJ-He)
Thanks for you work about semi-Semantic Segmentation .
I want to use you framework to train on my own tasks.
However,Some mistakes about dataloader I have meet,usually,we cann't have the same length about train and unsup-train data. So I have some errors on your framework.Do you have some solutions about this problems  Or  In your framework,what solutions you have done to solve this problems?

**Comment by yongjunhe11** [comment]
@angle011 If you cannot keep the same length of labeled and unlabeled data, you should modify the code of dataloader and training accordingly. In training section, you can try to set a variable to determine if all the labeled data has been go over one time, if yes, just skip supervised leanring part; if no, same as before. Hope that helps!

**Comment by angle011** [comment]
Thanks for your reply!
